version: "3.9"
   
services:
  master:
    hostname: master
    build:
      context: .
      dockerfile: Dockerfile
    image: federated_learning
    ports: 
      - "22"
    links: 
      - worker1
      - worker2
      # - worker3
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
      - ID=manager
      - TEST=${TEST}
      - EPOCHS=100000
      - MASTER=1
    depends_on:
      - worker1
      - worker2
      - worker3
      - worker4
    volumes:
      - ./results:/results/

  worker1: 
    image: federated_learning
    hostname: worker1
    environment:
      - ID=worker-1
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
      - TEST=${TEST}

  worker2: 
    image: federated_learning
    hostname: worker2
    environment:
      - ID=worker-2
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
      - TEST=${TEST}

  worker3: 
    image: federated_learning
    hostname: worker3
    environment:
      - ID=worker-3
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
      - TEST=${TEST}

  worker4: 
    image: federated_learning
    hostname: worker4
    environment:
      - ID=worker-4
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
      - TEST=${TEST}